{{$anamnese->id_tp}} <br>
{{$anamnese->id_paciente}} <br>
{{$anamnese->id_profissional}} <br>
{{$anamnese->compareceram_entrevista}} <br>
{{$anamnese->queixa}} <br>
{{$anamnese->escolaridade}} <br>
{{$anamnese->turno_das_aulas}} <br>
{{$anamnese->horario_das_aulas}} <br>
{{$anamnese->escola}} <br>
{{$anamnese->escola_publica_privada}} <br>
{{$anamnese->professor_responsavel}} <br>
{{$anamnese->coordenador}} <br>
{{$anamnese->encaminhado_pela_escola}} <br>
{{$anamnese->profissao_pai}} <br>
{{$anamnese->profissao_mae}} <br>
{{$anamnese->escolaridade_pai}} <br>
{{$anamnese->escolaridade_mae}} <br>
{{$anamnese->relacao_dos_pais_hoje}} <br>
{{$anamnese->outras_crianças_e_parentes_que_moram_com_a_criança}} <br>
{{$anamnese->tratamento_para_infertilidade}} <br>
{{$anamnese->historia_familiar_de_doenca_neurologica}} <br>
{{$anamnese->convulcoes}} <br>
{{$anamnese->como_era_composta_a_familia_na_epoca_da_concepcao}} <br>
{{$anamnese->idade_dos_pais_na_epoca_mãe}} <br>
{{$anamnese->idade_dos_pais_na_epoca_pai}} <br>
{{$anamnese->gestacoes_anteriores}} <br>
{{$anamnese->abortos}} <br>
{{$anamnese->naturais}} <br>
{{$anamnese->provocados}} <br>
{{$anamnese->perdeu_algum_filho}} <br>
{{$anamnese->a_perca_foi_antes_do_paciente}} <br>
{{$anamnese->como_perdeu_o_filho}} <br>
{{$anamnese->como_foi_a_aceitacao_das_familias}} <br>
{{$anamnese->gravidez_planejada_por_ambos}} <br>
{{$anamnese->fez_tratamento_pre_natal}} <br>
{{$anamnese->sofreu_acidentes_quedas_se_sim_como_foi}} <br>
{{$anamnese->teve_alguma_doenca_na_gestacao}} <br>
{{$anamnese->tomou_alguma_medicacao_se_sim_qual}} <br>
{{$anamnese->enjoo}} <br>
{{$anamnese->bebeu}} <br>
{{$anamnese->fumou}} <br>
{{$anamnese->entrou_em_contato_com_algum_produto_quimicotoxico_se_sim_qual}} <br>
{{$anamnese->esteve_em_ambientes_com_alto_nivel_de_poluicao}} <br>
{{$anamnese->exposição_a_raiox}} <br>
{{$anamnese->qual_era_a_situacao_economica_do_casal_na_epoca}} <br>
{{$anamnese->ja_tinham_outros_filhos_se_sim_quantos}} <br>
{{$anamnese->mae_trabalhava_fora_durante_gravidez}} <br>
{{$anamnese->casal_ou_familia_de_ambos_possui_doenca_hereditaria_se_sim_qual}} <br>
{{$anamnese->local_parto}} <br>
{{$anamnese->tipo_parto}} <br>
{{$anamnese->algum_problema_no_parto_se_sim_qual}} <br>
{{$anamnese->peso_ao_nascer}} <br>
{{$anamnese->comprimento_ao_nascer}} <br>
{{$anamnese->teve_ictericia}} <br>
{{$anamnese->idade_gestacional_do_bebe_ao_nascer}} <br>
{{$anamnese->como_se_deu_a_alimentação}} <br>
{{$anamnese->mamou_no_seio_se_nao_qual_o_motivo}} <br>
{{$anamnese->se_mamou_foi_ate_quando_e_como_se_sentia_ao_amamentar}} <br>
{{$anamnese->tomou_mamadeira_ate_quando}} <br>
{{$anamnese->aceitou_bem_a_alimentação_pastosa}} <br>
{{$anamnese->aceitou_bem_a_alimentação_solida}} <br>
{{$anamnese->alimentacao_atual}} <br>
{{$anamnese->retardo_diabetes_síndromes_doenças_nervosas_epilepsia}} <br>
{{$anamnese->teve_sarampo_infancia}} <br>
{{$anamnese->teve_dores_ouvido_infancia}} <br>
{{$anamnese->teve_colicas_infancia}} <br>
{{$anamnese->teve_catapora_infancia}} <br>
{{$anamnese->teve_caxumba_infancia}} <br>
{{$anamnese->teve_rubeola_infancia}} <br>
{{$anamnese->teve_coqueluche_infancia}} <br>
{{$anamnese->teve_meningite_infancia}} <br>
{{$anamnese->teve_desidratacao_infancia}} <br>
{{$anamnese->teve_otite_infancia}} <br>
{{$anamnese->teve_adenoides_infancia}} <br>
{{$anamnese->teve_amigdalites_infancia}} <br>
{{$anamnese->teve_alergias_infancia}} <br>
{{$anamnese->teve_acidentes_infancia}} <br>
{{$anamnese->teve_convulsoes_infancia}} <br>
{{$anamnese->teve_febres_infancia}} <br>
{{$anamnese->foi_internado_se_sim_por_quanto_tempo}} <br>
{{$anamnese->ja_fez_cirurgia_se_sim_com_quantos_anos_e_qual_cirugia}} <br>
{{$anamnese->quedas_e_traumatismos}} <br>
{{$anamnese->teve_complicacao_com_vacina_se_sim_qual}} <br>
{{$anamnese->audicao_e_visao}} <br>
{{$anamnese->sono_tranquilo_se_for_agitado_quando_e_qual_frequencia}} <br>
{{$anamnese->range_dentes}} <br>
{{$anamnese->terror_noturno}} <br>
{{$anamnese->sonambulistmo}} <br>
{{$anamnese->enurese}} <br>
{{$anamnese->fala_durante_sono}} <br>
{{$anamnese->dorme_so_se_nao_com_quem_dorme}} <br>
{{$anamnese->ate_quando_dormiu_com_os_pais}} <br>
{{$anamnese->como_foi_a_separacao_dormida_com_os_pais}} <br>
{{$anamnese->habitos_especiais_sono}} <br>
{{$anamnese->com_que_idade_sustentou_a_cabeca}} <br>
{{$anamnese->com_que_idade_sentou}} <br>
{{$anamnese->com_que_idade_engatinhou}} <br>
{{$anamnese->forma_de_engatinhar}} <br>
{{$anamnese->com_que_idade_comecou_a_andar}} <br>
{{$anamnese->caia_muito}} <br>
{{$anamnese->deixa_cair_as_coisas}} <br>
{{$anamnese->esbarra_muito}} <br>
{{$anamnese->acredita_que_apresenta_alguma_dificuldade_motora}} <br>
{{$anamnese->controle_vesical_bexiga}} <br>
{{$anamnese->controle_anal_fezes}} <br>
{{$anamnese->foi_difícil_tranquilo_ou_houve_algum_a_pressao_da_família}} <br>
{{$anamnese->balbucios}} <br>
{{$anamnese->quando_comecou_a_falar}} <br>
{{$anamnese->como_os_pais_reagiram_fala}} <br>
{{$anamnese->apresentou_problema_na_fala_se_sim_quais}} <br>
{{$anamnese->compreende_ordens}} <br>
{{$anamnese->presenca_de_bilinguismo_em_casa}} <br>
{{$anamnese->como_a_crianca_se_comunica}} <br>
{{$anamnese->apresenta_salivacao_no_canto_da_boca}} <br>
{{$anamnese->idade_entrou_na_escola}} <br>
{{$anamnese->adaptouse_bem}} <br>
{{$anamnese->metodo_alfabetizacao}} <br>
{{$anamnese->mudou_de_escola_se_sim_em_qual_serie_e_idade}} <br>
{{$anamnese->escola_atual}} <br>
{{$anamnese->metodo_alfabetizacao_atual}} <br>
{{$anamnese->professor}} <br>
{{$anamnese->faz_as_tarefaz_sozinho_se_nao_com_quem_faz}} <br>
{{$anamnese->descricao_momento_licoes}} <br>
{{$anamnese->fato_importante_vida_escolar}} <br>
{{$anamnese->queixas_frequentes}} <br>
{{$anamnese->tem_dificuldades_para}} <br>
{{$anamnese->conhece_tais_coisas}} <br>
{{$anamnese->apresenta_tiques_se_sim_quais}} <br>
{{$anamnese->como_pegua_o_lapis}} <br>
{{$anamnese->forca_da_escrita}} <br>
{{$anamnese->como_acha_que_surgiu_o_problema_a_que_fatores_atribuem}} <br>
{{$anamnese->outras_questoes}} <br>
{{$anamnese->escolas_que_frequentou}} <br>
{{$anamnese->repetiu_ano_se_sim_qual_e_porque}} <br>
{{$anamnese->humor_habitual}} <br>
{{$anamnese->prefere_brincar_sozinho_ou_em_grupos}} <br>
{{$anamnese->estranha_mudancas_de_ambiente}} <br>
{{$anamnese->adaptase_facilmente_ao_meio}} <br>
{{$anamnese->tem_horarios}} <br>
{{$anamnese->e_lider}} <br>
{{$anamnese->aceita_bem_ordens}} <br>
{{$anamnese->faz_birras}} <br>
{{$anamnese->chora_com_frequencia}} <br>
{{$anamnese->de_que_forma_e_punido}} <br>
{{$anamnese->pratica_esportes_se_sim_quais}} <br>
{{$anamnese->apresenta_agressividade_apatia_ou_teimosia}} <br>
{{$anamnese->tem_algum_medo_se_sim_quais}} <br>
{{$anamnese->quais_as_brincadeiras_e_brinquedos_favoritos}} <br>
{{$anamnese->quem_cuidava_da_criança_ate_os_tres_anos}} <br>
{{$anamnese->quem_cuida_posteriormente}} <br>
{{$anamnese->como_a_crianca_se_comporta_sozinha}} <br>
{{$anamnese->como_a_crianca_se_comporta_em_familia}} <br>
{{$anamnese->como_a_crianca_se_comporta_com_outras_pessoas}} <br>
{{$anamnese->com_quem_ele_mais_gosta_de_ficar_e_por_que}} <br>
{{$anamnese->em_que_momento_a_crianca_encontra_a_familia}} <br>
{{$anamnese->que_tipos_de_perdas_ja_enfrentou_e_em_que_idade}} <br>
{{$anamnese->ja_houve_conflitos_familiares_e_a_crianca_presencia}} <br>
{{$anamnese->assiste_tv_em_demasia}} <br>
{{$anamnese->quais_programas_favoritos}} <br>
{{$anamnese->de_que_forma_o_pai_e_a_mae_se_relacionam_com_a_crianca}} <br>
{{$anamnese->em_que_horario_brincam_ou_fazem_alguma_atividade_de_lazer}} <br>
{{$anamnese->como_se_relaciona_com_irmaos}} <br>
{{$anamnese->como_se_relaciona_com_colegas_e_professores}} <br>
{{$anamnese->apresenta_curiosidade_sexual_se_sim_quando_comecou}} <br>
{{$anamnese->tipos_de_perguntas_fase_sexual}} <br>
{{$anamnese->fase_de_masturbacao}} <br>
{{$anamnese->atitude_da_família}} <br>
{{$anamnese->se_veste_so_a_partir_de_qual_idade}} <br>
{{$anamnese->se_abotoa_so_a_partir_de_qual_idade}} <br>
{{$anamnese->fecha_roupa_so_a_partir_de_qual_idade}} <br>
{{$anamnese->toma_banho_so_a_partir_de_qual_idade}} <br>
{{$anamnese->se_penteia_so_a_partir_de_qual_idade}} <br>
{{$anamnese->se_amarra_so_a_partir_de_qual_idade}} <br>
{{$anamnese->escova_os_dentes_so_a_partir_de_qual_idade}} <br>
{{$anamnese->come_so_a_partir_de_qual_idade}} <br>
{{$anamnese->se_calca_so_a_partir_de_qual_idade}} <br>
{{$anamnese->roi_unhas}} <br>
{{$anamnese->tem_tiques_nervosos_se_sim_quais}} <br>
{{$anamnese->alguma_mania_repetitiva_se_sim_qual}} <br>
{{$anamnese->tem_movimentos_ritmicos}} <br>
{{$anamnese->chupa_dedo_ou_bico}} <br>
{{$anamnese->temObjetoComoCheirinhoOuOutroParaDormirLevarParaEscolaSeSimQual}} <br>
{{$anamnese->outros_habitos}} <br>
{{$anamnese->como_a_familia_ve_o_problema}} <br>
{{$anamnese->como_o_casal_age_em_funcao_da_crianca}} <br>
{{$anamnese->comoOsPaisSeVeemPermissivosAutoritariosEquilibradosEPorque}} <br>
{{$anamnese->como_sao_colocados_os_limites_para_a_crianca_no_seu_cotidiano}} <br>
{{$anamnese->situacao_economica}} <br>
{{$anamnese->situacao_cultural}} <br>
{{$anamnese->le_quais_livros_com_que_frequência}} <br>
{{$anamnese->vai_ao_cinema_e_com_que_frequencia}} <br>
{{$anamnese->estimulo_cultural_se_sim_quais}} <br>
{{$anamnese->habitos_de_lazer}} <br>
{{$anamnese->constancia_de_dialogos}} <br>
{{$anamnese->fazem_refeicoes_juntos_se_sim_quais}} <br>
{{$anamnese->algum_vício_na_família_se_sim_quais}} <br>
{{$anamnese->estabelece_contato_visual_se_sim_em_quais_situacoes}} <br>
{{$anamnese->imitaAlgumGestoDeEmocaoFamiliaresPessoasProximasSeSimQuais}} <br>
{{$anamnese->imita_algum_som_especifico_se_sim_quais}} <br>
{{$anamnese->mostrase_sonolento_se_sim_com_qual_frequencia}} <br>
{{$anamnese->quando_estimulado_consegue_relembrar_de_situacoes_vivenciadas}} <br>
{{$anamnese->com_que_frequencia_ignora_estimulos}} <br>
{{$anamnese->com_que_frequencia_manipula_brinquedos_e_objetos}} <br>
{{$anamnese->ansioso_no_processo_de_mudanca_de_rotina_se_sim_voce_lembra}} <br>
