{{$anamnese->id_paciente}} <br>
{{$anamnese->id_profissional}} <br>
{{$anamnese->gestacao}} <br>
{{$anamnese->doencas_da_mae_na_gravidez}} <br>
{{$anamnese->inquietacoes_da_mae_na_gravidez}} <br>
{{$anamnese->parto}} <br>
{{$anamnese->amamentacao_natural}} <br>
{{$anamnese->dificuldade_ou_atraso_no_controle_do_esfincter}} <br>
{{$anamnese->desenvolvimento_motor_no_tempo_certo}} <br>
{{$anamnese->perturbacoes_no_sono}} <br>
{{$anamnese->habitos_especiais_ao_dormir}} <br>
{{$anamnese->troca_letras_ou_fonemas}} <br>
{{$anamnese->dificuldade_na_fala}} <br>
{{$anamnese->dificuldade_na_visao}} <br>
{{$anamnese->dificuldade_na_locomocao}} <br>
{{$anamnese->movimentos_estereotipados}} <br>
{{$anamnese->ecolalias}} <br>
{{$anamnese->toma_banho_sozinho}} <br>
{{$anamnese->escova_os_dentes_sozinho}} <br>
{{$anamnese->usa_o_banheiro_sozinho}} <br>
{{$anamnese->necessita_auxilio_para_se_vestir_ou_despir}} <br>
{{$anamnese->idade_da_retirada_das_fraldas}} <br>
{{$anamnese->atende_intervencoes_quando_esta_desobedecendo}} <br>
{{$anamnese->chora_facil}} <br>
{{$anamnese->recusa_auxílio}} <br>
{{$anamnese->resistencia_ao_toque}} <br>
{{$anamnese->crianca_estuda}} <br>
{{$anamnese->ja_estudou_antes_em_outra_escola}} <br>
{{$anamnese->motivo_transferencia_escola_se_estudou_em_outra_antes}} <br>
{{$anamnese->ja_repetiu_alguma_serie}} <br>
{{$anamnese->possui_acompanhante_terapeutico_em_sala}} <br>
{{$anamnese->recebe_orientacao_aos_deveres_em_casa}} <br>
{{$anamnese->quem_orienta_os_deveres_em_casa_se_sim_orientacao_deveres}} <br>
{{$anamnese->quanto_tempo_executa_os_deveres_em_casa}} <br>
{{$anamnese->quais_linguas_estrangeiras_fala}} <br>
{{$anamnese->quais_esportes_pratica}} <br>
{{$anamnese->quais_intrumentos_toca}} <br>
{{$anamnese->outras_atividades_que_pratica}} <br>
{{$anamnese->faz_amigos_com_facilidade}} <br>
{{$anamnese->adaptase_facilmente_ao_meio}} <br>
{{$anamnese->companheiros_da_crianca_em_brincadeiras}} <br>
{{$anamnese->escolha_de_grupo}} <br>
{{$anamnese->distracoes_preferidas}} <br>
{{$anamnese->obediente}} <br>
{{$anamnese->dependente}} <br>
{{$anamnese->comunicativo}} <br>
{{$anamnese->agressivo}} <br>
{{$anamnese->cooperativo}} <br>
{{$anamnese->descricao_se_sim_dependente}} <br>
{{$anamnese->descricao_se_sim_indepedente}} <br>
{{$anamnese->descricao_se_sim_agressivo}} <br>
{{$anamnese->descricao_se_sim_cooperador}} <br>
{{$anamnese->tranquilo}} <br>
{{$anamnese->seguro}} <br>
{{$anamnese->ansioso}} <br>
{{$anamnese->emotivo}} <br>
{{$anamnese->alegre}} <br>
{{$anamnese->queixoso}} <br>
{{$anamnese->insonia}} <br>
{{$anamnese->pesadelos}} <br>
{{$anamnese->hipersonia}} <br>
{{$anamnese->dorme_sozinho}} <br>
{{$anamnese->dorme_no_quarto_dos_pais}} <br>
{{$anamnese->divide_quarto_com_alguem}} <br>
{{$anamnese->medidas_disciplinares_empregadas_pelos_pais}} <br>
{{$anamnese->reação_do_filho_ao_ser_contrariado}} <br>
{{$anamnese->atitude_dos_pais_a_reacao_filho_contrareado}} <br>
{{$anamnese->acompanhamento_medico}} <br>
{{$anamnese->qual_medico_responsavel}} <br>
{{$anamnese->diagnostico_medico}} <br>
