<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class AgendamentosAutSeeds extends Seeder {

    public function run()
    {
        include('database/seeds/SeedsConfig.php');
        include_once('database/seeds/FuncoesAuxuliaresSeeds.php');

        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Vera Agatha Raimunda Assis',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Rosa Renata Santos',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Henry José Enzo Santos',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Benício Luís Renan Castro',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Raimunda Jaqueline Sarah Assis',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Thiago Hugo das Neves',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Cauã Mário Antonio da Luz',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Bruna Fátima Lima',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Theo Pietro da Conceição',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);
        DB::table('agendamentos')->insert([
            'id_convenio' => rand(1, $qtd_convenios),
            'id_profissional' => rand(1, $qtd_profissionals),
            'nome' => 'Melissa Lavínia Daniela Lima',
            'cpf' => (string)rand(10000000000, 99999999999),
            'data_nascimento_paciente' => Carbon::now()->format('Y-m-d H:i:s'),
            'telefone' => (string)rand(10000000000, 99999999999),
            'email' => Str::random(7) . '@gmail.com',
            'id_endereco' => rand(1, $qtd_enderecos),
            'data_entrada' => Carbon::now()->format('Y-m-d H:i:s'),
            'data_saida' => Carbon::now()->format('Y-m-d H:i:s'),
            'local_de_atendimento' => 'Clínica',
            'recorrencia_do_agendamento' => rand(0, 1) >= 0.5,
            'tipo_da_recorrencia' => Str::random(10),
            'observacoes' => '',
            'status' => rand(0, 1) >= 0.3,
        ]);

    }
}
