<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class PacientesAutSeeder extends Seeder {

    public function run()
    {
        include('database/seeds/SeedsConfig.php');
        include_once('database/seeds/FuncoesAuxuliaresSeeds.php');

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Luís Vitor Bruno Gonçalves',
            'cpf' => '10349162891',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Danilo Calebe Gonçalves',
            'numero_irmaos' => 0,
            'lista_irmaos' => '',
            'nome_pai' => 'Danilo Calebe Gonçalves',
            'nome_mae' => 'Elaine Silvana Eduarda',
            'telefone_pai' => '8237940947',
            'telefone_mae' => '82986436125',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'Salvador-BA',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => '',
            'vive_com_quem_caso_pais_divorciados' => 'Pai',
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => '',
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Eduarda Simone Rosa Jesus',
            'cpf' => '46557834274',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Luzia Maitê Evelyn',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Gustavo Juan Jesus',
            'nome_mae' => 'Luzia Maitê Evelyn',
            'telefone_pai' => '8529104755',
            'telefone_mae' => '85983283202',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'Recife-PE',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => texto(5),
            'vive_com_quem_caso_pais_divorciados' => '',
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => '',
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Regina Lorena Louise da Silva',
            'cpf' => '76203322270',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Simone Maya',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Ruan Cauê Tomás da Silva',
            'nome_mae' => 'Simone Maya',
            'telefone_pai' => '9625400537',
            'telefone_mae' => '96985322216',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'Garanhuns-PE',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => '',
            'vive_com_quem_caso_pais_divorciados' => Str::random(20),
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => '',
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Vicente Kevin Emanuel Cavalcanti',
            'cpf' => '10149903863',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Cauê Erick Cavalcanti',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Cauê Erick Cavalcanti',
            'nome_mae' => 'Heloise Fabiana Esther',
            'telefone_pai' => '7436885584',
            'telefone_mae' => '74995590540',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'São Paulo-SP',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => '',
            'vive_com_quem_caso_pais_divorciados' => '',
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => '',
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Paulo Juan das Neves',
            'cpf' => '41018707727',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Amanda Helena',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Carlos Kauê Antonio das Neves',
            'nome_mae' => 'Amanda Helena',
            'telefone_pai' => '6127690411',
            'telefone_mae' => '61991868205',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'Garanhuns-PE',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => '',
            'vive_com_quem_caso_pais_divorciados' => 'Mãe',
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => '',
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Mário Theo Rocha',
            'cpf' => '',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Henry Kauê Vitor Rocha',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Henry Kauê Vitor Rocha',
            'nome_mae' => 'Rayssa Carla Laís',
            'telefone_pai' => '9627232060',
            'telefone_mae' => '96998913220',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'Caruaru-PE',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => texto(5),
            'vive_com_quem_caso_pais_divorciados' => Str::random(20),
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => texto(2),
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Felipe Henrique Victor Drumond',
            'cpf' => '24357741688',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Lívia Nina',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Yuri Joaquim Drumond',
            'nome_mae' => 'Lívia Nina',
            'telefone_pai' => '1127105180',
            'telefone_mae' => '11983513435',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'Aracaju-SE',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => texto(5),
            'vive_com_quem_caso_pais_divorciados' => Str::random(20),
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => texto(2),
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Mariana Carolina Cardoso',
            'cpf' => '41299514162',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Giovana Larissa',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Noah Paulo Vinicius Cardoso',
            'nome_mae' => 'Giovana Larissa',
            'telefone_pai' => '7329528631',
            'telefone_mae' => '73987613755',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'Rio de Janeiro-RJ',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => texto(5),
            'vive_com_quem_caso_pais_divorciados' => Str::random(20),
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => texto(2),
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Bento Emanuel Peixoto',
            'cpf' => '64338182423',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Aurora Sophie Josefa',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Julio Yuri Sebastião Peixoto',
            'nome_mae' => 'Aurora Sophie Josefa',
            'telefone_pai' => '8126696076',
            'telefone_mae' => '81989436741',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'Recife-PE',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => texto(5),
            'vive_com_quem_caso_pais_divorciados' => Str::random(20),
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => texto(2),
        ]);

        DB::table('pacientes')->insert([
            'login' => "PacienteLogin" . rand(1, 10000),
            'password' => Hash::make("123123123"),
            'nome_paciente' => 'Fernanda Luana da Mota',
            'cpf' => '11067673229',
            'sexo' => rand(0, 1) >= 0.5,
            'data_nascimento' => Carbon::now()->format('Y-m-d H:i:s'),
            'responsavel' => 'Elisa Marcela Emilly',
            'numero_irmaos' => rand(0, 10),
            'lista_irmaos' => '',
            'nome_pai' => 'Gabriel Miguel Rafael da Mota',
            'nome_mae' => 'Elisa Marcela Emilly',
            'telefone_pai' => '6335961746',
            'telefone_mae' => '63996955363',
            'email_pai' => Str::random(7) . '@gmail.com',
            'email_mae' => Str::random(7) . '@gmail.com',
            'idade_pai' => rand(20, 100),
            'idade_mae' => rand(20, 100),
            'id_endereco' => rand(1, $qtd_enderecos),
            'naturalidade' => 'João Pessoa-PB',
            'pais_sao_casados' => rand(0, 1) >= 0.5,
            'pais_sao_divorciados' => rand(0, 1) >= 0.5,
            'reacao_sobre_a_relacao_pais_caso_divorciados' => texto(5),
            'vive_com_quem_caso_pais_divorciados' => Str::random(20),
            'tipo_filho_biologico_adotivo' => rand(0, 1) >= 0.5,
            'crianca_sabe_se_adotivo' => rand(0, 1) >= 0.5,
            'reacao_quando_descobriu_se_adotivo' => texto(2),
        ]);
    }
}
