{{$avaliacao->id}} <br>
{{$avaliacao->id_paciente}} <br>
{{$avaliacao->id_profissional}} <br>
{{$avaliacao->motivo_avaliacao}} <br>
{{$avaliacao->data_avaliacao}} <br>
{{$avaliacao->ultima_tarefa_correta_linguagem_receptiva}} <br>
{{$avaliacao->menos_total_respostas_incorretoas_linguagem_receptiva}} <br>
{{$avaliacao->linguagem_receptiva}} <br>
{{$avaliacao->ultima_tarefa_correta_linguagem_expressiva}} <br>
{{$avaliacao->menos_total_respostas_incorretoas_linguagem_expressiva}} <br>
{{$avaliacao->linguagem_expressiva}} <br>
{{$avaliacao->ultima_tarefa_correta_linguagem_global}} <br>
{{$avaliacao->menos_total_respostas_incorretoas_linguagem_global}} <br>
{{$avaliacao->linguagem_global}} <br>
{{$avaliacao->observacao_comportamento}} <br>
