{{$avaliacao->id}} <br>
{{$avaliacao->id_paciente}} <br>
{{$avaliacao->id_profissional}} <br>
{{$avaliacao->diagnostico}} <br>
{{$avaliacao->resposta_emocional}} <br>
{{$avaliacao->uso_do_corpo}} <br>
{{$avaliacao->uso_de_objetos}} <br>
{{$avaliacao->adaptacao_a_mudancas}} <br>
{{$avaliacao->resposta_auditiva}} <br>
{{$avaliacao->resposta_visual}} <br>
{{$avaliacao->medo_ou_nervosismo}} <br>
{{$avaliacao->comunicacao_verbal}} <br>
{{$avaliacao->orienta_se_por_som}} <br>
{{$avaliacao->comunicacao_nao_verbal}} <br>
{{$avaliacao->orienta_se_por_som}} <br>
{{$avaliacao->reacao_ao_nao}} <br>
{{$avaliacao->compreendem_comandos_simples_palavras_que_descrevam_objetos}} <br>
{{$avaliacao->manipula_brinquedos_objetos}} <br>
{{$avaliacao->equilibrio}} <br>
{{$avaliacao->forca}} <br>
{{$avaliacao->resistencia}} <br>
{{$avaliacao->marcha}} <br>
{{$avaliacao->agilidade}} <br>
{{$avaliacao->coordenacao_motora_fina}} <br>
{{$avaliacao->coordenacao_motora_grossa}} <br>
{{$avaliacao->propriocepcao}} <br>
{{$avaliacao->compreende_direcoes}} <br>
{{$avaliacao->compreende_comandos_professoras}} <br>
{{$avaliacao->concentracao}} <br>
{{$avaliacao->comportamento_reflexo}} <br>
{{$avaliacao->observacoes}} <br>
{{$avaliacao->terapias}} <br>
{{$avaliacao->objetivos}} <br>
{{$avaliacao->tipo_da_aula}} <br>
