{{$avaliacao->id_paciente}} <br>
{{$avaliacao->id_profissional}} <br>
{{$avaliacao->id_anaminese}} <br>
{{$avaliacao->queixa_principal}} <br>
{{$avaliacao->encaminhado_por}} <br>
{{$avaliacao->participantes_durante_anaminese}} <br>
{{$avaliacao->descricao_das_funcoes_cognitivas_avaliadas}} <br>
{{$avaliacao->testes_neuropsicologicos}} <br>
{{$avaliacao->recursos_complementares}} <br>
{{$avaliacao->dias_necessarios_para_avaliacao_justificados_se_mais_que_4_dias}} <br>
{{$avaliacao->alimentacao_nos_dias_da_avalicao}} <br>
{{$avaliacao->sono_nos_dias_da_avalicao}} <br>
{{$avaliacao->higiene_nos_dias_da_avalicao}} <br>
{{$avaliacao->humor_nos_dias_da_avalicao}} <br>
{{$avaliacao->areas_preservadas}} <br>
{{$avaliacao->areas_lesionadas}} <br>
{{$avaliacao->anexar_arquivos}} <br>
{{$avaliacao->hipotese_diagnostica}} <br>
{{$avaliacao->dia_hora_devolutiva_aos_responsavel}} <br>
{{$avaliacao->participantes}} <br>
{{$avaliacao->atividades_para_ser_feito_na_clinica}} <br>
{{$avaliacao->atividades_para_ser_feito_em_casa}} <br>
{{$avaliacao->sugestao_encaminhamento}} <br>
{{$avaliacao->exames_clinicos_se_houver}} <br>
