{{$avaliacao->id_paciente}} <br>
{{$avaliacao->id_profissional}} <br>
{{$avaliacao->data_avaliacao}} <br>
{{$avaliacao->entrevistado}} <br>
{{$avaliacao->queixa_principal}} <br>
{{$avaliacao->brincadeiras_favoritas}} <br>
{{$avaliacao->onde_brinca}} <br>
{{$avaliacao->com_quem_prefere_brincar}} <br>
{{$avaliacao->o_que_faz_rir}} <br>
{{$avaliacao->brincadeiras_evitadas}} <br>
{{$avaliacao->brinca_sozinho_ou_precisa_de_atencao}} <br>
{{$avaliacao->postura_crianca_quando_brinca}} <br>
{{$avaliacao->reacao_ao_ser_frustrada_ou_raiva}} <br>
{{$avaliacao->quem_disciplina_a_crianca}} <br>
{{$avaliacao->como_reage_a_orientacao_dos_pais}} <br>
{{$avaliacao->reacao_a_abracos_carinhos}} <br>
{{$avaliacao->areas_maior_habilidade}} <br>
{{$avaliacao->areas_maior_dificuldade}} <br>
{{$avaliacao->hora_de_levantar}} <br>
{{$avaliacao->hora_cafe_da_manha}} <br>
{{$avaliacao->hora_da_escola}} <br>
{{$avaliacao->hora_almoco}} <br>
{{$avaliacao->hora_janta}} <br>
{{$avaliacao->hora_dormir}} <br>
{{$avaliacao->dorme_durante_dia}} <br>
{{$avaliacao->dorme_com_facilidade}} <br>
{{$avaliacao->sono_tranqulo}} <br>
{{$avaliacao->acorda_noite}} <br>
{{$avaliacao->pesadelos}} <br>
{{$avaliacao->sonambulismo}} <br>
{{$avaliacao->rola_balanca_cabeca_enquanto_dorme}} <br>
{{$avaliacao->come_com_os_dedos}} <br>
{{$avaliacao->come_com_talheres}} <br>
{{$avaliacao->brinca_com_comida}} <br>
{{$avaliacao->derrama_comida}} <br>
{{$avaliacao->usa_mao_direita_para_comer}} <br>
{{$avaliacao->bebe_em_garrafa}} <br>
{{$avaliacao->usa_canudo}} <br>
{{$avaliacao->segura_copo_garrafa_com_uma_ou_duas_maos}} <br>
{{$avaliacao->ajuda_a_colocar_a_mesa}} <br>
{{$avaliacao->tipo_alimentacao}} <br>
{{$avaliacao->tem_bom_apetite}} <br>
{{$avaliacao->o_que_gosta_de_comer}} <br>
{{$avaliacao->nao_gosta_de_comer}} <br>
{{$avaliacao->houve_dificuldade_transicao_pastoso_solido}} <br>
{{$avaliacao->gosta_de_vestir_roupa}} <br>
{{$avaliacao->veste_roupa_sozinho_quais_pecas}} <br>
{{$avaliacao->tira_roupa_sozinho_quais_pecas}} <br>
{{$avaliacao->abotoa}} <br>
{{$avaliacao->amarra}} <br>
{{$avaliacao->usa_fralda}} <br>
{{$avaliacao->usa_vaso_sanitario}} <br>
{{$avaliacao->lava_maos_face_corpo}} <br>
{{$avaliacao->escova_dentes}} <br>
{{$avaliacao->se_diverte_com_o_banho}} <br>
{{$avaliacao->gosta_molhar_cabeca}} <br>
{{$avaliacao->enxuga_se}} <br>
{{$avaliacao->gosta_pentear_cabelos}} <br>
{{$avaliacao->gosta_cortar_cabelos}} <br>
{{$avaliacao->gosta_cortar_unhas}} <br>
{{$avaliacao->info_extras_relevante}} <br>
